# Generated by Django 4.2.13 on 2024-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("image", models.CharField(max_length=100)),
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("animal_name", models.CharField(max_length=50)),
                ("animal_price", models.IntegerField()),
                ("animal_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_category",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_gender",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="animal_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_picture",
            field=models.CharField(),
        ),
    ]
