# Generated by Django 4.2.13 on 2024-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="animal_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_age",
            field=models.CharField(max_length=10),
        ),
    ]
