# Generated by Django 4.2.13 on 2024-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_orders_animal_name_alter_animal_animal_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_category",
            field=models.CharField(default="Milk", max_length=40),
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_gender",
            field=models.CharField(default="Male", max_length=10),
        ),
    ]
