# Generated by Django 4.2.13 on 2024-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_animal_animal_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="animal_age",
            field=models.IntegerField(),
        ),
    ]
