# Generated by Django 4.2.13 on 2024-05-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_options_animal_animal_category_and_more"),
        ("api", "0004_alter_animal_animal_age"),
    ]

    operations = []
