# Generated by Django 4.2.13 on 2024-05-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_animal_animal_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("animal_picture", models.CharField()),
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("animal_name", models.CharField(max_length=50)),
                ("animal_price", models.IntegerField()),
                ("animal_description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
