# Generated by Django 4.2.13 on 2024-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_accesstoken_cart_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewCart",
            fields=[
                ("image", models.CharField(max_length=50)),
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
