# Generated by Django 4.2.13 on 2024-05-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_viewcart"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("animal_picture", models.CharField()),
                ("animal_id", models.AutoField(primary_key=True, serialize=False)),
                ("animal_name", models.CharField(max_length=50)),
                ("animal_type", models.CharField(max_length=50)),
                ("animal_age", models.IntegerField()),
                ("animal_location", models.CharField(max_length=30)),
                ("animal_breed", models.CharField(max_length=20)),
                ("available", models.IntegerField()),
                ("animal_price", models.IntegerField()),
                ("animal_description", models.CharField(max_length=200)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="api.farmer",
                    ),
                ),
            ],
        ),
    ]
